include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_unused_constructor_parameters: true
    unnecessary_const: true
    unnecessary_this: true
    avoid_returning_null_for_void: true
    prefer_single_quotes: true
